### ISSUE TITLE
Bug in amount handling

### ISSUE THREAD

**Issue by syntaxerror** [DIBS-Payment-Services/VirtueMart#10]
Seems like the plugin has quite a few problems handling amounts
- on specials, discounts, coupons etc.

> Amount does not match total amount from order rows.

**Comment by syntaxerror** [comment]
Unchecking 'Configuration -> Pricing -> Round only display' seems to help, but then the calculation in VM gets less accurate.

**Comment by syntaxerror** [comment]
Note! The issue is easier to recreate if there is 2 or more of the same product in cart, having special, discount etc. applied to it.

**Comment by maxwhite** [comment]
Ok, thanks I'll check
