### ISSUE TITLE
Bad error handling

### ISSUE THREAD

**Issue by syntaxerror** [DIBS-Payment-Services/VirtueMart#2]
In cases where the payment is fine at DIBS, it's really a bad thing to display a confusing error message to the customer. You should instead (in background) log those to a log file in the log folder, and notifying the store owner by mail so he/she can check the log (both is supported by VirtueMart and Joomla).

T.ex. in cases where you returns a wrong key (#41), which seems to be related to MC payments...

For others where the payment has failed, the order should be pending or cancelled, and a proper and understandable error message displayed within normal Joomla/VM error display.

You're only confusing the customers with the error handling you have now, which often leads them to try to place the order twice, and thus also paying twice (or more). Anyhow, they get pissed of by it...

**Comment by maxwhite** [comment]
Thanks we will look at that
