### ISSUE TITLE
Different URL's in FW and PW, why?

### ISSUE THREAD

**Issue by syntaxerror** [DIBS-Payment-Services/VirtueMart#4]
Any reasons for using different URL formatting in the FW and PW plugin, they are for the same VM versions right?

Ref.:
- https://github.com/DIBS-Payment-Services/VirtueMart/blob/master/src/DIBSFW/dibs_api/fw/dibs_fw_helpers.php#L240-L242
- https://github.com/DIBS-Payment-Services/VirtueMart/blob/master/src/DIBSPW/dibs_api/pw/dibs_pw_helpers.php#L306-L308

**Comment by maxwhite** [comment]
Yes, we cannot use url with params for DIBS FlexWn:
"The URL of the page to be displayed if the purchase is approved.
You cannot use parameters in the URL. Example. ”?X=4&Y=2” The URLs have to be ”clean"."
You can read about it here:
http://tech.dibspayment.com/D2/Hosted/Input_parameters/Standard

**Comment by syntaxerror** [comment]
They could still be the same, but OK.
