### ISSUE TITLE
carturl

### ISSUE THREAD

**Issue by syntaxerror** [DIBS-Payment-Services/VirtueMart#5]
What is the "carturl" used for?

It can't work for all as it's now anyway, so if it's in use it needs a change:
- https://github.com/DIBS-Payment-Services/VirtueMart/blob/master/src/DIBSFW/dibs_api/fw/dibs_fw_helpers.php#L243
- https://github.com/DIBS-Payment-Services/VirtueMart/blob/master/src/DIBSPW/dibs_api/pw/dibs_pw_helpers.php#L309

T.ex. if the store is a "subsite", having it's own menu item named "webshop", the non-SEF URL would t.ex be "index.php/webshop/cart/" and not "index.php/cart/" ...

**Comment by maxwhite** [comment]
This url is not used in payment flow, so it cannot produce any error, I think we will remove it, thanks :)
